### ISSUE TITLE
quiz0

### ISSUE THREAD

**Issue by rklein3** [emory-courses/cs329#10]
I am having a problem creating a project (part of quiz0.   I am getting a Java.Language.NullPointerException error when trying to create a new package called src/quiz/.   Any ideas about how to address this?
rk

**Comment by SichangTu** [comment]
Hi, please try to create the package with `src.quiz.`. This would work without raising the error.

**Comment by rklein3** [comment]
That works.  Thanks!
rk
________________________________
From: Sichang TU ***@***.***>
Sent: Thursday, January 13, 2022 11:37 AM
To: emory-courses/computational-linguistics ***@***.***>
Cc: Klein, Robin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [emory-courses/computational-linguistics] quiz0 (Issue #10)


Hi, please try to create the package with src.quiz.. This would work without raising the error.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femory-courses%2Fcomputational-linguistics%2Fissues%2F10%23issuecomment-1012307716&data=04%7C01%7Crklein3%40emory.edu%7Cf2a02975a00740ce19dc08d9d6b30e56%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637776886796698505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vWH1hkLwnJ4%2Bo7kW8FOvwVt%2Bw6yEErhmcgXsVrM1QEc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXJILE2YIVRSSZ563TIUWNDUV35WLANCNFSM5L4JSZ7Q&data=04%7C01%7Crklein3%40emory.edu%7Cf2a02975a00740ce19dc08d9d6b30e56%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637776886796708498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pAVSItPEeXfK84B2YTFaQqnliKLaOFOoj8DDBH7%2BY00%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crklein3%40emory.edu%7Cf2a02975a00740ce19dc08d9d6b30e56%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637776886796718498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H9E1hj33RjREBDbAWIEd%2BDKubNtpFi2lubXpPi78EEg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crklein3%40emory.edu%7Cf2a02975a00740ce19dc08d9d6b30e56%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637776886796728485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rLImwfXWnkTrG%2F4vmPc5n6v2aRCa8y5GLZaq%2FRoDn7s%3D&reserved=0>.
