### ISSUE TITLE
[QZ0] package or directory

### ISSUE THREAD

**Issue by kristinagxy** [emory-courses/cs329#11]
Hello! I know in quiz 0 we need to create a package src/quiz for the quizes.
<img width="707" alt="Screen Shot 2022-01-13 at 4 47 04 PM" src="https://user-images.githubusercontent.com/91505624/149414153-7d30de2e-9574-42f4-92d6-0b6c02949a9d.png">

But later it is said the src/quiz is a directory.
<img width="674" alt="Screen Shot 2022-01-13 at 4 49 18 PM" src="https://user-images.githubusercontent.com/91505624/149414409-835062e6-aa31-4319-bcff-dcda128b883d.png">

I noticed when I click "add" in pycharm, I can choose to create a package or a directory. So I wonder which one shall I create? Thank you!!! :)

**Comment by hxysophy** [comment]
Hi! After you create the package called src.quiz, you should be able to see the src/quiz/ directory.

**Comment by kristinagxy** [comment]
> Hi! After you create the package called src.quiz, you should be able to see the src/quiz/ directory.

Got it, thank you!
