### ISSUE TITLE
[QZ0] Pushed .idea and venv by accident

### ISSUE THREAD

**Issue by talynfan** [emory-courses/cs329#12]
![Screenshot (36)](https://user-images.githubusercontent.com/89471624/149439937-7d11021c-73e4-4def-b49c-1205cf85733b.png)

The first time I committed and pushed, I think my .gitignore didn't work right because everything, including the .idea and venv folders, got pushed to my repo. I tried it again but I can't figure out how to get rid of them. How do I make my repo have only the files it's supposed to have? Do I have to start over? (I'm fairly new to using github, so sorry if this seems like a silly question.)

Also, the src folder should be under the main cs329 directory, _not_ under .idea, correct?

**Comment by hxysophy** [comment]
Hi - It is correct that the src folder should be under the main cs329 directory, _not_ under .idea. 

To remove the .idea and venv folders, you would first add your .idea and venv to .gitignore by right-clicking on them in PyCharm. Then you would have to untrack them first by entering the following two lines in your temrinal:
`git rm -r --cached .idea`
`git rm -r --cashed venv`
After this, add your .gitignore to Git and push your changes. You could try this to see if it solves your problem.

**Comment by talynfan** [comment]
Thanks, your advice worked.

One note: when I used PyCharm to add the folders to .gitignore instead of manually typing them in, the folder names had backslashes in front of them. This is different from the Quiz 0 instructions. But it worked.

![Screenshot (37)](https://user-images.githubusercontent.com/89471624/149680433-02040f83-5f07-4e48-98f2-d38aebe03e46.png)
