### ISSUE TITLE
[QZ0] push rejected

### ISSUE THREAD

**Issue by kristinagxy** [emory-courses/cs329#13]
Hello, when I click push there occurred an error message saying the push is rejected because remote changes need to be pushed before merging

<img width="476" alt="Screen Shot 2022-01-14 at 1 32 29 AM" src="https://user-images.githubusercontent.com/91505624/149462254-06acb0ad-d13d-40de-9e47-5972f679f649.png">

Here is what I got before the push. Under the push there is another choice called force push. Do I need to click force push instead of push? Thank you!!

<img width="901" alt="Screen Shot 2022-01-14 at 1 33 00 AM" src="https://user-images.githubusercontent.com/91505624/149462308-169fdf5c-1dd5-4c2c-8a76-b0e232b21864.png">

**Comment by hxysophy** [comment]
Hi, if you wish to merge the remote branch into your local branch, you could do a pull first (right click on your project folder -> Git -> Pull from main) and then push to Git. If you believe that your local branch is the most up-to-date and there's nothing from the remote branch that you want to merge, you could do a force push.

**Comment by kristinagxy** [comment]
> 

Thank you!! I pushed successfully

**Comment by hxysophy** [comment]
Awesome! Closing this issue now.
