### ISSUE TITLE
[QZ0] URL Submitted on Canvas Shows 404

### ISSUE THREAD

**Issue by EulaFRL** [emory-courses/cs329#14]
I copied the URL to my cs329 repository and submitted it on canvas, but the canvas page shows this. Is this fine?
<img width="1200" alt="截屏2022-01-14 下午4 32 56" src="https://user-images.githubusercontent.com/97711833/149588312-611e6178-4c34-434f-b1f4-4f2f45fa2924.png">

**Comment by hxysophy** [comment]
Hi - I'm able to see your repository. You're all good.

**Comment by EulaFRL** [comment]
> Hi - I'm able to see your repository. You're all good.

Thank you.
