### ISSUE TITLE
Lecture Recordings

### ISSUE THREAD

**Issue by EulaFRL** [emory-courses/cs329#15]
Where should I find the recording for yesterday's lecture? Thank you.

**Comment by talynfan** [comment]
It's on the schedule, as a hyperlink on the 1/13 "String Matching" topic. 

https://github.com/emory-courses/computational-linguistics/blob/master/docs/schedule.md

**Comment by EulaFRL** [comment]
> It's on the schedule, as a hyperlink on the 1/13 "String Matching" topic.
> 
> https://github.com/emory-courses/computational-linguistics/blob/master/docs/schedule.md

Thank you！
