### ISSUE TITLE
[QZ1] git push

### ISSUE THREAD

**Issue by kristinagxy** [emory-courses/cs329#23]
Hello! This is actually a trivial question XD But after I pushed my quiz1, as I checked my repository, I find my quiz0.py and quiz0.ipynb have been pushed again automatically as well. Is there a way to stop this from happening and push only quiz1.py?

**Comment by SichangTu** [comment]
Hi, there are two simple ways you can do this:

1. In the Pycharm version control window, check the file you want to commit and push. In your case, check quiz1.py only.
<img width="613" alt="Screen Shot 2022-01-29 at 3 35 00 PM" src="https://user-images.githubusercontent.com/58782296/151676924-1bab9ed8-73c9-46ce-8f62-3f0faceb5d79.png">

2. Use terminal commands in the Pycharm.  `git commit -m '<commit message>' <path to the file>` and then `git push`. In your case, replace the path to the file with `src/quiz/quiz1.py`. Make sure you've added the `quiz1.py` to git before you commit and push.

**Comment by kristinagxy** [comment]
Got it! Thank you
