### ISSUE TITLE
[QZ3] Using NLTK for Quiz 3

### ISSUE THREAD

**Issue by zinczhao** [emory-courses/cs329#31]
Does any one know whether we are allowed to use NLTK for quiz 3? If we are allowed to use NLTK for quiz 3, would we lose points if the NLTK is not installed on the grader's computer and cause the program to fail its compiling process? (Considering that we are likely to lose all the points for a quiz if our program does not compute.)

**Comment by jdchoi77** [comment]
@ZincZhao You are not allowed to use NLTK for Quiz 3 (or any other package). If you just download the [ELIT pos-tagger](http://github.com/emorynlp/elit) and run, it would give 98% accuracy on this data, which would have no meaning.
