### ISSUE TITLE
match object .start(g) method 

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/cs329#6]
In the python docs example m = re.search('b(c?)', 'cba'), what does the 1 in n.start(1) means?  and why is it 2? Thankyou

@jdchoi77

**Comment by jdchoi77** [comment]
@caroltang0331 could you give me the context of this code? It's hard for me to tell what `n` is.  In general, the `start(1)` would give the starting offset of the first group matched.

**Comment by caroltang0331** [comment]
I'm sorry I think I meant m instead of n. I have attached the context. The document said it creates a substring matched by group but I'm a bit confused on what it means. Thank you 

![Screen Shot 2021-02-12 at 9 52 11 AM](https://user-images.githubusercontent.com/69888386/107722092-29555400-6d19-11eb-9da8-ac5c04503f92.png)
