### ISSUE TITLE
[QZ#2] Question about the test case "'boy.n.01' and 'girl.n.01'"

### ISSUE THREAD

**Issue by kxiao02** [emory-courses/cs329#8]
Hello everyone! 

I was playing with my paths method using different test cases, and I somehow found that the hypernym_paths() method call of "boy.n.01" returned two paths that both lead to the leaf "male_child.n.01" instead of "boy.n.01". "girl.n.01" works totally fine, but it didn't show 'female_child.n.01' anywhere in the hypernym paths.

Does it mean that I am using the hypernym_paths() method in a wrong way? Will this cause problems when my paths method is put through the test cases?

Please help.

**Comment by jdchoi77** [comment]
@kxiao02 this is normal; NLTK uses the ID of the first item in the synset to represent the entire synset so this behavior is expected. Please see the updated description of Quiz 2.

**Comment by kxiao02** [comment]
> @kxiao02 this is normal; NLTK uses the ID of the first item in the synset to represent the entire synset so this behavior is expected. Please see the updated description of Quiz 2.

Thank you!
